#!/bin/bash

if [ -f .env ]
then
	source .env
fi

if [ -z "${ADMIN_USERNAME}" ]
then
	read -p "Choose a username to protect the admin site with: "
	echo -e "Username: \"${REPLY}\""

	echo "ADMIN_USERNAME=${REPLY}" >> .env
fi

if [ -z "${ADMIN_PASSWORD}" ]
then
	prompt="Choose a password to protect the admin site with: "
	while IFS= read -p "${prompt}" -r -s -n 1 char
	do
		if [[ "${char}" == $'\0' ]]
		then
			echo -e "\n"
			break
		fi
		prompt='*'
		password+="$char"
	done

	echo "ADMIN_PASSWORD=${password}" >> .env
fi

script/bootstrap
